version: 2.1

jobs:
  build:
    docker:
      - image: 'python:3.6'
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: 'python:3.6'
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  integration:
    docker:
      - image: 'python:3.6'
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
          allow_failures: true

  prod:
    docker:
      - image: 'python:3.6'
    steps:
      - checkout
      - run: echo "This is a deploy step"

  artifacts:
    docker:
      - image: 'python:3.6'
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Create Artifacts
          command: |
            # Create the artifacts (e.g., build outputs, reports, files) in the /workspace directory
            # Ensure that the artifacts are placed in /workspace so they can be accessed in subsequent jobs
            echo "Creating artifacts..."
            mkdir -p /workspace/artifacts
            echo "This is an example artifact" > /workspace/artifacts/artifact.txt
            # Add any other artifact creation steps here

workflows:
  version: 2
  django:
    jobs:
      - build
      - test
      - integration
      - prod
      - artifacts:
          requires:
            - build
            - test
            - integration
